version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
    commit-message:
      prefix: 'github-actions'
      include: 'scope'

  - package-ecosystem: 'docker'
    directory: "/"
    schedule:
      interval: 'daily'
      time: '09:00'
    commit-message:
      prefix: 'docker'
      include: 'scope'
